### PR TITLE
Support alphabetic name generation for @n attributes > 26

### PR DESCRIPTION
**Pull request by th-we**
The current way of getting from `@n` attributes to proper Lilypond names only works up to 26. Also, it repeats the same logic in a lot of places, which is avoided by this pull request.

### CODE REVIEW

**Review by rettinghaus — COMMENTED** [review]
This was intentional. Who would need more than 26 staves? 
I'd be happy to replace fn:codepoints-to-string with a new function, but your way brings more XSLT 2.0 stuff in. Could you make a XSLT 1.0 version?

**Comment by th-we** [comment]
In Ligeti's Atmosphères, the violins alone already have 28 staves.  (I suppose the question was ironic.)

Well, XSLT 1.0 doesn't have functions, so this would IMO overcomplicate things. I saw you were planning to run this transformation in the browser. Can you explain why you would do that? As Lilypond does not run in the browser, a server would have to be involved anyway.

**Comment by rettinghaus** [comment]
I finally made a branch for XSLT 1.0 (which will be paused for the moment) so we can focus on XSLT 2.0. 
@th-we Can you remove the conflict so I may merge your pull request?

**Comment by th-we** [comment]
This should be ready to merge now.

**Pull request merged**
